---

apiVersion: v1
kind: Service
metadata:
  name: aws-secrets
  labels:
    run: aws-secrets
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    run: aws-secrets
  type: NodePort

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aws-secrets
spec:
  serviceName: aws-secrets
  selector:
    matchLabels:
      run: aws-secrets
  replicas: 1
  template:
    metadata:
      labels:
        run: aws-secrets
    spec:
      containers:
        - name: aws-secrets
          image: aws-secrets:0.0.1-SNAPSHOT
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: IS_STATEFUL_SET
              value: "1"
            # Using env variables instead of Service Account :-)
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: aws_secret_access_key
            - name: AWS_REGION
              value: "eu-west-2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-aws-secrets
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /aws-secrets/$2
spec:
  ingressClassName: nginx
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /aws-secrets(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: aws-secrets
                port:
                  number: 80