spring.config.import:
  - optional:aws-secretsmanager:/stacks-secret/example-1/
  - optional:aws-secretsmanager:/stacks-secret/example-2/

server:
  servlet:
    context-path: /aws-secrets
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80