spring.config.import:
  - aws-secretsmanager:/secret/backend
  - aws-secretsmanager:/stacks/aws/demo

server:
  servlet:
    context-path: /aws-secrets
  port: 8080

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 80